### ISSUE TITLE
W18: Invalid character in group name

### ISSUE THREAD

**Issue by oblitum** [kristijanhusak/defx-icons#1]
I'm trying your plugin and I'm getting lots of this when running `:Defx -columns=icons:filename:type`:

```
Error detected while processing function defx#util#call_defx[2]..defx#start[8]..defx#util#rpcrequest[11].._defx_start[1]..remote#define#request:
line    2:
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
.
.
.
```

Despite that,  defx still opens up with the folder and file icons fine.

**Comment by oblitum** [comment]
~~Just `:Defx -columns=icons:filename`, for some reason, avoids the problem.~~

**Comment by oblitum** [comment]
My bad, it doesn't avoid it. The issue is that the errors show up only the first time I run the command.

**Comment by oblitum** [comment]
Issue does stop with `let g:defx_icons_enable_syntax_highlight = 0`, but icons lose their colors :(

**Comment by kristijanhusak** [comment]
I think it's issue with naming of some highlight groups. Can you just tell me what you use:

1. Vim/neovim and it's version
2. OS

**Comment by oblitum** [comment]
1. NeoVim 0.3.1
2. ArchLinux

**Comment by kristijanhusak** [comment]
Update and give it a test, should be working now.

**Comment by oblitum** [comment]
@kristijanhusak it has reduced the number of errors a lot, but I still get two W18.

**Comment by oblitum** [comment]
Last error from `v:errmsg` is `E28: No such highlight group name: Defx_type`.

**Comment by oblitum** [comment]
After debugging, this is the reason:

```
syntax match Defx_icons_c++ /[]/ contained containedin=Defx_icons
syntax match Defx_icons_f# /[]/ contained containedin=Defx_icons
```

"F#" and "C++" names.

**Comment by oblitum** [comment]
It may be worth using `self.vim.command_output` for when it's nonempty to raise meaningful errors in (Neo)Vim. The current error message isn't helpful.

**Comment by oblitum** [comment]
I didn't analyze all the code but from this error, it seems a usual solution is to use a numerical hash function over  names, to protect from problematic names, and then prepend this hash with a header and use it to create the group names: `safe_name = 'dfx_' + hash('F#')`.

**Comment by oblitum** [comment]
It could be also a solution for the initial fix. I'm not sure whether it's just stripping chars now, which can easily generate collisions.

**Comment by kristijanhusak** [comment]
I'm not sure why you get these errors. I don't get any on manjaro linux and linux mint with neovim 0.3.2-dev, even before the previous fix.

I don't want to use hashing in case someone wants to override some color.

I removed c++ and f# from the extensions dictionary. As far as i know, file extensions with that exact name does not exist. for c++ it's cpp, and for f# it's fs. Correct me if i'm wrong.

Update and give it a test.

**Comment by oblitum** [comment]
I get no more errors, but at least for c++, the extension does  exist. I can't say for F# because I don't use it. In fact `.c++` historically was supposed to be the de-facto standard c++ extension, but the creator of the language has stated that DOS/Windows blocked that. Despite `.cpp` and `.cc` being the most used ones, there are some projects that use `.c++`.

**Comment by oblitum** [comment]
I'm closing the issue since it fixes the issue for me, but maybe not for some lost soul adopting those extensions.

**Comment by oblitum** [comment]
Thanks!

**Comment by kristijanhusak** [comment]
Didn't knew that, thanks for info. I'll leave it as it is, if someone really gets issue with those extensions (i doubt it), i'll add it back and properly strip it. Thanks for reporting.

**Comment by oblitum** [comment]
OK. If I could recall which project I've seen sometime ago using `.c++` I'd put it here as example, it's rare but does exist. I simply forgot which was it.
